apiVersion: v1
kind: Pod
metadata:
  name: test
  labels: test-pod
spec:
  containers:
    - name: test-container
      image: rapa.iptime.org:5000/nginx:jje
---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
spec:
  selector:
    app: test-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
